# This rule is not used by the project heat-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to heat.openstack.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: heat-operator
    app.kubernetes.io/managed-by: kustomize
  name: heatcfnapi-viewer-role
rules:
- apiGroups:
  - heat.openstack.org
  resources:
  - heatcfnapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - heat.openstack.org
  resources:
  - heatcfnapis/status
  verbs:
  - get
