apiVersion: heat.openstack.org/v1beta1
kind: Heat
metadata:
  name: heat
spec:
  customServiceConfig: "# add your customization here"
  databaseInstance: openstack
  databaseUser: "heat"
  rabbitMqClusterName: rabbitmq
  debug:
    dbSync: false
    service: false
  heatAPI:
    containerImage: "quay.io/podified-antelope-centos9/openstack-heat-api:current-podified"
    customServiceConfig: "# add your customization here"
    debug:
      dbSync: false
      service: false
    replicas: 1
    resources: {}
    secret: osp-secret
  heatCfnAPI:
    containerImage: "quay.io/podified-antelope-centos9/openstack-heat-api-cfn:current-podified"
    customServiceConfig: "# add your customization here"
    debug:
      dbSync: false
      service: false
    replicas: 1
    resources: {}
    secret: osp-secret
  heatEngine:
    containerImage: "quay.io/podified-antelope-centos9/openstack-heat-engine:current-podified"
    customServiceConfig: "# add your customization here"
    debug:
      dbSync: false
      service: false
    replicas: 1
    resources: {}
    secret: osp-secret
  passwordSelectors:
    service: HeatPassword
    database: HeatDatabasePassword
  preserveJobs: false
  secret: osp-secret
  serviceUser: "heat"
