apiVersion: heat.openstack.org/v1beta1
kind: Heat
metadata:
  name: heat
spec:
  customServiceConfig: |
    [DEFAULT]
    debug = True
  databaseInstance: openstack
  databaseUser: "heat"
  rabbitMqClusterName: rabbitmq
  debug:
    dbSync: false
  heatAPI:
    debug:
      service: false
    resources: {}
  heatCfnAPI:
    debug:
      service: false
    resources: {}
  heatEngine:
    debug:
      service: false
    resources: {}
  preserveJobs: false
  secret: osp-secret
  serviceUser: "heat"
